### ISSUE TITLE
Performing type erasure

### ISSUE THREAD

**Issue by tanishqkancharla** [julienvincent/ts-codec#1]
What's the best way to coerce a specific codec type to a less specific codec type? Using `as` gives me type errors:

```ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[]

const codec = t.object({
  id: t.string
}) as t.Codec<{id: string}, Json>
```
I expect this to work because `Json` is a less specific type then `{ id: string }`, so I should be able to coerce it's output type correctly.

Here's the error:

```
Conversion of type 'ObjectCodec<{ id: IdentityCodec<CodecType.String>; }>' to type 'Codec<{ id: string; }, JSON, string, CodecProps>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  The types of 'meta(...).encode' are incompatible between these types.
    Type 'Transformer<MappedIx<WithOptional<{ id: IdentityCodec<CodecType.String>; }>>, MappedOx<WithOptional<{ id: IdentityCodec<CodecType.String>; }>>>' is not comparable to type 'Transformer<{ id: string; }, JSON>'.
      Type 'MappedOx<WithOptional<{ id: IdentityCodec<CodecType.String>; }>>' is not comparable to type 'JSON'.
```

and here's a sandbox:

https://codesandbox.io/s/romantic-phoebe-mblpmm?file=/src/index.tsx

**Comment by julienvincent** [comment]
This wouldn't really be a supported use of the lib. Can you speak a bit on what your use-case is? I don't understand why you would need to do this conversion at the codec level.

**Comment by tanishqkancharla** [comment]
I have a generic interface for a block (which is some runtime construct). The block needs to specify how it wants to encode/decode its state to Json. Ideally, I can just describe the shape of the type, and it will be Json-friendly.

```ts
// BlockApi.ts
export type BlockApi<BlockState extends BaseState> = {
	codec: t.Codec<BlockState, Json>
}

// LoginBlock.ts
export type LoginBlockState = {
	id: string
	type: "login"
	title: "Login"
}

export const loginApi: BlockApi<LoginBlockState> = {
	// Type error
	codec: t.object({
		id: t.string,
		type: t.literal("login"),
		title: t.literal("Login"),
	}),
}
```

Even though, this shape of the login block state is definitely json-friendly, the codec doesn't allow it. It can't always just be the identity codec though, other blocks might contain state that needs explicit serialization/deserialization logic.

**Comment by tanishqkancharla** [comment]
I was able to get around this by not making my api reliant on `ts.codec`:

```ts
// BlockApi.ts
export type BlockApi<BlockState extends BaseState> = {
  codec: {
    encode: (state: BlockState) => Json
    decode: (json: any) => BlockState
  }
}
```
